update:
	(cd local/coq-plugin-lib;    git pull -r; git submodule update --recursive)
	(cd local/fix-to-elim;       git pull -r; git submodule update --recursive)
	(cd local/ornamental-search; git pull -r; git submodule update --recursive)
	(cd local/PUMPKIN-PATCH;     git pull -r; git submodule update --recursive)
