extra-deps:
- crackNum-2.3
- dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
- fgl-visualize-0.1.0.1
- FloatingHex-0.4@sha256:05f65f2b0103d98574b2a2b4a592e02d83ebb13bdbad347b9157507165cf51e7
- GraphSCC-1.0.4
- IfElse-0.85
- monadLib-3.8
- panic-0.4.0.1
- sbv-7.13
- simple-smt-0.9.3
packages:
  - '.'
  - '../abcBridge'
  - '../aig'
  - '../crucible/crucible'
  - '../crucible/crucible-jvm'
  - '../crucible/crucible-llvm'
  - '../crucible/crucible-saw'
  - '../crucible/crux'
  - '../cryptol'
  - '../cryptol-verifier'
  - '../dwarf'
  - '../elf-edit'
  - '../flexdis86'
  - '../flexdis86/binary-symbols'
  - '../jvm-parser'
  - '../jvm-verifier'
  - '../llvm-pretty'
  - '../llvm-pretty-bc-parser'
  - '../llvm-verifier'
  - '../macaw/base'
  - '../macaw/symbolic'
  - '../macaw/x86'
  - '../macaw/x86_symbolic'
  - '../parameterized-utils'
  - '../saw-core'
  - '../saw-core-aig'
  - '../saw-core-coq'
  - '../saw-core-sbv'
  - '../saw-core-what4'
  - '../crucible/what4'
resolver: lts-12.16
