extra-deps:
  - GraphSCC-1.0.4
  - crackNum-2.3
  - FloatingHex-0.4
  - monadLib-3.8
  - panic-0.4.0.1
  - simple-smt-0.9.3
packages:
  - '.'
  - '../abcBridge'
  - '../aig'
  - '../crucible/crucible'
  - '../crucible/crucible-saw'
  - '../crucible/what4'
  - '../cryptol'
  - '../parameterized-utils'
  - '../saw-core'
  - '../saw-core-aig'
  - '../saw-core-sbv'
  - '../saw-core-what4'
  - '../sbv'
resolver: lts-12.16
